---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-repo-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: e2e-nextjs-
      spec:
        pipelineRef:
          name: e2e-nextjs
        serviceAccountName: build-bot
        params:
            - name: app-name
              value: e2e-nextjs
            - name: source-repo
              value: https://github.com/cloud-native-garage-method-cohort/rd-so-nextjs.git
            - name: image-repo
              value: quay.io/stephan_orlowsky/rd-so-nextjs
        workspaces:
          - name: e2e-build
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: production-repository
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
