apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-nextjs
spec:
  params:
    - name: app-name
      type: string
      description: Application name
    - name: source-repo
      type: string
      description: Source code repository
    - name: sha
      type: string
      default: ""
      description: Precise SHA of the commit to build
    - name: image-repo
      type: string
      description: Docker image repository
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: "$(params.source-repo)"
        - name: revision
          value: "$(params.sha)"
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: e2e-build
    - name: run-tests
      params:
        - name: ARGS
          value:
            - install-ci-test
      runAfter:
        - clone-repository
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: e2e-build
    - name: create-image
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      runAfter:
        - clone-repository
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: e2e-build
    - name: create-configuration
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: commit
          value: "$(tasks.clone-repository.results.commit)"
        - name: image-repo
          value: "$(params.image-repo)"
        - name: runtime
          value: "js"
        - name: source-repo
          value: "$(params.source-repo)"
      runAfter:
        - clone-repository
      taskRef:
        name: create-configuration
      workspaces:
        - name: source
          workspace: e2e-build
    - name: deploy
      params:
        - name: manifest
          value: "$(tasks.create-configuration.results.manifest)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
      runAfter:
        - create-configuration
        - create-image
      taskRef:
        name: deploy
      workspaces:
        - name: source
          workspace: e2e-build
    - name: save-configuration
      params:
        - name: manifest
          value: "$(tasks.create-configuration.results.manifest)"
        - name: app-name
          value: "$(params.app-name)"
        - name: sha
          value: "$(tasks.clone-repository.results.commit)"
      runAfter:
        - deploy
      taskRef:
        name: save-configuration
      workspaces:
        - name: source
          workspace: e2e-build
        - name: target
          workspace: production-repository
  workspaces:
    - name: e2e-build
    - name: production-repository